AWSTemplateFormatVersion: '2010-09-09'
Description: |
  [ v1.2.0 ] 17 Mar 2026 - Creates the AWS Secret required for setup of Uptime Kuma and its initialization.
  Keep the parameters consistent across all three Kuma templates to ensure proper resource linking.  
  Suggested stackname: uptime-kuma-secret-stack

Parameters:
  ProjectName:
    Type: String
    Default: uptime-kuma
    Description: Mandatory tag. Name of the project (lowercase only, hyphens allowed).
  Disambiguation:
    Type: String
    Default: k-01
    Description: Disambiguation string to ensure unique resource names. (lowercase only, hyphens allowed)
  Environment:
    Type: String
    Default: production
    Description: Environment name (e.g., development, staging, production)
    AllowedValues:
      - development
      - staging
      - production

Resources:
  KumaAWSSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: kuma-secret
      Description: Secrets needed for Uptime Kuma
      SecretString: |
        {
          "webhook": "placeholder",
          "channel": "placeholder",
          "username": "placeholder",
          "password": "placeholder"
        }
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Disambiguation
          Value: !Ref Disambiguation
        - Key: Environment
          Value: !Ref Environment

Outputs:
    
  ActionRequired:
    Description: Edit the secret to replace placeholders
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/secretsmanager/home?region=${AWS::Region}#!/secret?name=${KumaAWSSecret}'
