authentication:
  ORG: "my-org"
  REPO: "my-repo"
  GITHUB_TOKEN: "ghp_***"

variables:
  A: "value for A"
  AA: "value for AA"

secrets:
  B: "secret value for B"
  BB: "secret value for BB"
